image: node:latest

stages:
  - test

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - yarn
    - yarn test:ci
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml